# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: Kelsey_02201993
  CLOUD_SQL_DATABASE_NAME: project
  CLOUD_SQL_CONNECTION_NAME: cmsc508-project-258320:us-central1:myinstance
# [END gae_python37_cloudsql_config]